on:
  push:
    tags:
      - 2.0.0.*
      - 1.0.[0-9]+
      - 2.[0-9]+.[0-9]+

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: wurmlab/sequenceserver:latest,wurmlab/sequenceserver:${{ github.ref_name }}
